spring.application.name=shop

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SOK\
  ;encrypt=true;trustServerCertificate=true;
spring.datasource.username=admin
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


spring.jpa.hibernate.ddl-auto=update

server.servlet.session.persistent=false

